// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQaUfr9Oxky9dyDjhonTTMWwaUefoBBdk',
    appId: '1:1014328533077:web:ea222cc965ac3dec7534dc',
    messagingSenderId: '1014328533077',
    projectId: 'appinventario-de2e8',
    authDomain: 'appinventario-de2e8.firebaseapp.com',
    storageBucket: 'appinventario-de2e8.firebasestorage.app',
    measurementId: 'G-LLNYZZSC9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGosmJK2dZUzFErTAG9JwiaYM_tUXvTuU',
    appId: '1:1014328533077:android:a1f11adb8790eccb7534dc',
    messagingSenderId: '1014328533077',
    projectId: 'appinventario-de2e8',
    storageBucket: 'appinventario-de2e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmCzc-QBzNbVbovJMrsmz6yP-jk7i38O8',
    appId: '1:1014328533077:ios:2cd3587174679a747534dc',
    messagingSenderId: '1014328533077',
    projectId: 'appinventario-de2e8',
    storageBucket: 'appinventario-de2e8.firebasestorage.app',
    iosBundleId: 'com.example.appinventario',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmCzc-QBzNbVbovJMrsmz6yP-jk7i38O8',
    appId: '1:1014328533077:ios:2cd3587174679a747534dc',
    messagingSenderId: '1014328533077',
    projectId: 'appinventario-de2e8',
    storageBucket: 'appinventario-de2e8.firebasestorage.app',
    iosBundleId: 'com.example.appinventario',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQaUfr9Oxky9dyDjhonTTMWwaUefoBBdk',
    appId: '1:1014328533077:web:6250cf2e3699dd3f7534dc',
    messagingSenderId: '1014328533077',
    projectId: 'appinventario-de2e8',
    authDomain: 'appinventario-de2e8.firebaseapp.com',
    storageBucket: 'appinventario-de2e8.firebasestorage.app',
    measurementId: 'G-7PGFEVRK8P',
  );
}
